"""
AlienCore - license_pubkey.py
Embedded Ed25519 public key used to verify license payloads returned by the
backend (/auth/verify-pin and /auth/check).

This file is checked into source control on purpose — it is the public half
of an Ed25519 keypair generated by tools/generate_license_keypair.py.  The
private half lives only on the backend and is never written to the client.

Threat model: see core/license_signing.py.

To regenerate (NEVER do this casually — it invalidates every existing
license signature in the wild):
  1. python tools/generate_license_keypair.py --out-dir <secure-location> --force
  2. Replace PUBLIC_KEY_B64 below with the new license_public.b64 contents.
  3. Set AC_LICENSE_PRIVATE_KEY on the backend to the new PEM contents.
  4. Ship a client update — old clients won't trust new signatures, and
     vice versa, so the rollout requires a versioned cutover.
"""

# Base64-encoded raw 32-byte Ed25519 public key.
# REPLACE THIS PLACEHOLDER with the contents of license_public.b64 generated
# by tools/generate_license_keypair.py before the v1.0 release.  An empty or
# all-zero key is detected by core/license_signing.py and forces all license
# checks to fail closed — no Pro features unlock until a real key is shipped.
PUBLIC_KEY_B64 = ""
