"""
AlienCore - license_pubkey.py
Embedded Ed25519 public key used to verify license payloads returned by the
backend (/auth/verify-pin and /auth/check).

This file is checked into source control on purpose — it is the public half
of an Ed25519 keypair generated by tools/generate_license_keypair.py.  The
private half lives only on the backend and is never written to the client.

Threat model: see core/license_signing.py.

To regenerate (NEVER do this casually — it invalidates every existing
license signature in the wild):
  1. python tools/generate_license_keypair.py --out-dir <secure-location> --force
  2. Replace PUBLIC_KEY_B64 below with the new license_public.b64 contents.
  3. Set AC_LICENSE_PRIVATE_KEY on the backend to the new PEM contents.
  4. Ship a client update — old clients won't trust new signatures, and
     vice versa, so the rollout requires a versioned cutover.
"""

# Base64-encoded raw 32-byte Ed25519 public key.
# Generated 2026-05-02 by tools/generate_license_keypair.py.  The matching
# private key lives only on the production backend — it never appears in
# source control, the .exe installer, or any client-side artifact.
PUBLIC_KEY_B64 = "RlA+GKrtZT9vH0oYM//PHE6S1X0XE9pSJGJx2UZNnvA="
